#!/bin/bash

# Kivy installer for Raspberry Pi.
# A quick and easy way to get the Kivy framework installed on your Pi
# Adapted from "http://kivy.org/docs/installation/installation-rpi.html"
# & https://github.com/mrichardson23/rpi-kivy-screen

# Gregory Parker 2015

# Ensure the script is invoked by the root user
if [ "$(id -u)" -ne 0 ] ; then
        echo "You must invoke this script as root. Try using 'sudo'"
        exit 1
fi

# Add vontaene repository for the installation of gstreamer
sudo /bin/su -c "echo 'deb http://vontaene.de/raspbian-updates/ . main' >> /etc/apt/sources.list"

# Add the APT key for vontaene
gpg --recv-keys 0C667A3E
gpg -a --export 0C667A3E | sudo apt-key add -

# Update the package list and install dependencies
apt-get update
apt-get -y --force-yes install pkg-config libgl1-mesa-dev libgles2-mesa-dev \
   python-pygame python-setuptools libgstreamer1.0-dev git-core \
   gstreamer1.0-plugins-{bad,base,good,ugly} \
   gstreamer1.0-{omx,alsa} python-dev

# Acquire and install pip
wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
python get-pip.py

# Use pip to install cython and pygments   
pip install cython pygments docutils

# Get kivy from git
git clone https://github.com/kivy/kivy
cd kivy

# Install kivy system-wide
python setup.py build
python setup.py install

# Go to root's home directory and delete the kivy folder, to save space
cd ~
rm -rf kivy
